### ISSUE TITLE
❓ [Question] My aten::chunk op converter does not work correctly

### ISSUE THREAD

**Issue by letian-jiang** [NVIDIA/TRTorch#523]
## ❓ Question

I want to use trtorch to compile shufflenet. However, aten::chunk op is not currently supported. I wrote a converter implementation referring to `converters/impl/select.cpp`. Unfortunately, it does not work.

Is there anything wrong? 

The python code
```python 
model = torchvision.models.shufflenet_v2_x1_0(pretrained=True).cuda().eval()
input_data = torch.randn(1, 3, 224, 224).cuda()
scripted_model = torch.jit.script(model)
out = scripted_model(input_data)

compile_settings = {
    "input_shapes": [(1, 3, 224, 224)],
}

trt_ts_module = trtorch.compile(scripted_model, compile_settings)
```

The converter I wrote (compared with the converter of `aten::select`, I only changed `numOuputs` and `sizes`)
```cpp
auto chunk_registrations TRTORCH_UNUSED =
    RegisterNodeConversionPatterns()
        .pattern({"aten::chunk(Tensor(a) self, int chunks, int dim=0) -> (Tensor[])",
                  [](ConversionCtx* ctx, const torch::jit::Node* n, args& args) -> bool {
                    auto in = args[0].ITensor();
                    auto numOutputs = args[1].unwrapToInt();
                    auto axis = args[2].unwrapToInt();
                    auto inDimSize = in->getDimensions().d[axis];
                    LOG_DEBUG("Number of chunk outputs: " << numOutputs);
                    std::vector<int64_t> sizes;

                    if (inDimSize % numOutputs == 0) {
                        for (int64_t i = 0; i < numOutputs; i++) {
                            sizes.push_back(inDimSize / numOutputs);
                        }
                    }
                    else {
                        for (int64_t i = 0; i < numOutputs - 1; i++) {
                            sizes.push_back(inDimSize / numOutputs + 1);
                        }
                        sizes.push_back(inDimSize - (inDimSize / numOutputs + 1) * (numOutputs - 1));
                    }

                    c10::ListTypePtr lt = n->output()->type()->expect<c10::ListType>();
                    c10::TypePtr elementType = lt->getElementType();
                    auto list = c10::impl::GenericList(elementType);
                    list.reserve(numOutputs);

                    int start_idx = 0;
                    for (int64_t i = 0; i < numOutputs; i++) {
                        at::Tensor indices = torch::arange(start_idx, start_idx + sizes[i], 1).to(torch::kI32);
                        auto indicesTensor = tensor_to_const(ctx, indices);

                        auto gather_layer = ctx->net->addGather(*in, *indicesTensor, axis);
                        auto gather_out = gather_layer->getOutput(0);

                        auto tensor_holder = TensorContainer();
                        tensor_holder.hold_tensor(gather_out);
                        auto ival = c10::IValue(std::move(c10::make_intrusive<TensorContainer>(tensor_holder)));
                        list.emplace_back(ival);

                        start_idx = start_idx + sizes[i];
                    }

                    auto chunk_output_ivalue = std::move(torch::jit::IValue(list));
                    ctx->AssociateValueAndIValue(n->outputs()[0], chunk_output_ivalue);

                    LOG_DEBUG("Converted chunk op into a list of IValues");
                    return true;
                  }});
```
DEBUG log
```
INFO: [TRTorch Conversion Context] - Adding Layer %78 : Tensor[] = aten::chunk(%input.152, %self.stage2.0.stride, %self.stage2.1.stride) # /opt/conda/lib/python3.8/site-packages/torchvision/models/shufflenetv2.py:89:21 (ctx.AddLayer)
DEBUG: [TRTorch Conversion Context] - Node input is an already converted tensor
DEBUG: [TRTorch Conversion Context] - Node input is a result of a previously evaluated value
DEBUG: [TRTorch Conversion Context] - Node input is a result of a previously evaluated value
DEBUG: [TRTorch] - Number of chunk outputs: 2
DEBUG: [TRTorch] - Weights: [58]
    Number of input maps: 58
    Number of output maps: 58
    Element shape: [1]
DEBUG: [TRTorch Conversion Context] - Freezing tensor 0x7fbb1c37c4e0 as an IConstantLayer
DEBUG: [TRTorch] - Weights: [58]
    Number of input maps: 58
    Number of output maps: 58
    Element shape: [1]
DEBUG: [TRTorch Conversion Context] - Freezing tensor 0x7fbb1be22d30 as an IConstantLayer
DEBUG: [TRTorch] - Converted chunk op into a list of IValues
DEBUG: [TRTorch Conversion Context] - Evaluating %x1.9 : Tensor, %x2.9 : Tensor = prim::ListUnpack(%78)
DEBUG: [TRTorch Conversion Context] - Found the evaluated value(s) to be True for node: %x1.9 : Tensor, %x2.9 : Tensor = prim::ListUnpack(%78)
DEBUG: [TRTorch Conversion Context] - Found the evaluated value(s) to be True for node: %x1.9 : Tensor, %x2.9 : Tensor = prim::ListUnpack(%78)
DEBUG: [TRTorch Conversion Context] - Evaluating %81 : Float(58, 58, 1, 1, strides=[58, 1, 1, 1], requires_grad=0, device=cuda:0) = prim::Constant[value=<Tensor>]()
DEBUG: [TRTorch Conversion Context] - Found the value to be a tensor (shape [58, 58, 1, 1])
INFO: [TRTorch Conversion Context] - Adding Layer %82 : Tensor = aten::_convolution(%x2.9, %81, %7, %9, %11, %9, %10, %11, %self.stage2.1.stride, %10, %10, %10, %10) (ctx.AddLayer)
DEBUG: [TRTorch Conversion Context] - Node input is a result of a previously evaluated value
DEBUG: [TRTorch Conversion Context] - Node input is a result of a previously evaluated value
DEBUG: [TRTorch Conversion Context] - Node input is a result of a previously evaluated value
DEBUG: [TRTorch Conversion Context] - Node input is a result of a previously evaluated value
DEBUG: [TRTorch Conversion Context] - Node input is a result of a previously evaluated value
DEBUG: [TRTorch Conversion Context] - Node input is a result of a previously evaluated value
DEBUG: [TRTorch Conversion Context] - Node input is a result of a previously evaluated value
DEBUG: [TRTorch Conversion Context] - Node input is a result of a previously evaluated value
DEBUG: [TRTorch Conversion Context] - Node input is a result of a previously evaluated value
DEBUG: [TRTorch Conversion Context] - Node input is a result of a previously evaluated value
DEBUG: [TRTorch Conversion Context] - Node input is a result of a previously evaluated value
DEBUG: [TRTorch Conversion Context] - Node input is a result of a previously evaluated value
DEBUG: [TRTorch Conversion Context] - Node input is a result of a previously evaluated value
Traceback (most recent call last):
  File "test_shuffle_net.py", line 27, in <module>
    trt_ts_module = trtorch.compile(scripted_model, compile_settings)
  File "/opt/conda/lib/python3.8/site-packages/trtorch/_compiler.py", line 73, in compile
    compiled_cpp_mod = trtorch._C.compile_graph(module._c, _parse_compile_spec(compile_spec))
RuntimeError: [Error thrown at core/conversion/var/Var.cpp:149] Expected isITensor() to be true but got false
Requested ITensor from Var, however Var type is c10::IValue
```

**Comment by narendasan** [comment]
I think that all you need to do is replace `auto in = args[0].ITensor();` with `auto in = args[0].ITensorOrFreeze()`. The difference is that ITensorOrFreeze can handle the case where the argument is an `ITensor` like `args.ITensor()` and the case where the arg is a PyTorch Tensor by creating a IConstantLayer and giving you the ITensor output back.

**Comment by letian-jiang** [comment]
Thanks for your advice! I replaced `ITensor()` with `ITensorOrFreeze(ctx)` in the converter of `aten::_convolution` and it works.
